#pragma once

#include "KeyWords.hpp"

KeyWord keywords[] = {
	{ .num = LEX_ALL,				.string = L"всё",									},
	{ .num = LEX_FORGET,			.string = L"позабыл",								},
	{ .num = LEX_JUMPED,			.string = L"прыгнул",								},
	{ .num = LEX_CO,				.string = L"со",									},
	{ .num = LEX_MOUNTAIN,			.string = L"скалы",									},
	{ .num = LEX_WILD,				.string = L"дикий",									},
	{ .num = LEX_SCREAM,			.string = L"крик",									},
	{ .num = LEX_EMIT,				.string = L"издав",									},
	{ .num = LEX_BUT,				.string = L"но",									},
	{ .num = LEX_HAPPENED,			.string = L"вышло",									},
	{ .num = LEX_NO,				.string = L"не",									},
	{ .num = LEX_SO,				.string = L"так",									},
	{ .num = LEX_ON,				.string = L"на",									},
	{ .num = LEX_DINNER,			.string = L"ужин",									},
	{ .num = LEX_INVITED,			.string = L"пригласил",								},
	{ .num = LEX_CAME_IN,			.string = L"зашёл",									},
	{ .num = LEX_IN,				.string = L"в",										},
	{ .num = LEX_DEADLOCK,			.string = L"тупик",									},
	{ .num = LEX_ONE,				.string = L"один",									},
	{ .num = LEX_LEAST,				.string = L"лишь",									},
	{ .num = LEX_ONLY,				.string = L"только",								},
	{ .num = LEX_PATH,				.string = L"путь",									},
	{ .num = LEX_WENT,				.string = L"шёл",									},
	{ .num = LEX_TO_HOME,			.string = L"домой",									},
	{ .num = LEX_RUMBLES,			.string = L"грохочет",								},
	{ .num = LEX_THUNDER,			.string = L"гром",									},
	{ .num = LEX_SPARKLES,			.string = L"сверкает",								},
	{ .num = LEX_LIGHTNING,			.string = L"молния",								},
	{ .num = LEX_EDGE,				.string = L"краю",									},
	{ .num = LEX_HILL,				.string = L"холме",									},
	{ .num = LEX_WAS_FALLING,		.string = L"наступала",								},
	{ .num = LEX_NIGHT,				.string = L"ночь",									},
	{ .num = LEX_HAPPINESS,			.string = L"счастье",								},
	{ .num = LEX_GAIN,				.string = L"обрёл",									},
	{ .num = LEX_TIME,				.string = L"времени",								},
	{ .num = LEX_LESS,				.string = L"меньше",								},
	{ .num = LEX_DEVOTES,			.string = L"посвящает",								},
	{ .num = LEX_INTERESTING,		.string = L"интерес",								},
	{ .num = LEX_HUGE,				.string = L"большой",								},
	{ .num = LEX_FOUND,				.string = L"нашёл",									},
	{ .num = LEX_DONT_ENOUGH,		.string = L"хватило",								},
	{ .num = LEX_POWER,				.string = L"силы",									},
	{ .num = LEX_VERY,				.string = L"весьма",								},
	{ .num = LEX_STUBBORN,			.string = L"упрям",									},
	{ .num = LEX_DIFFERENCE,		.string = L"отличие",								},
	{ .num = LEX_FUNNY,				.string = L"смешной",								},
	{ .num = LEX_ADVICE,			.string = L"совет",									},
	{ .num = LEX_HE,				.string = L"он",									},
	{ .num = LEX_KNOW,				.string = L"знает",									},
	{ .num = LEX_VO,				.string = L"во",									},
	{ .num = LEX_DARKNESS,			.string = L"мраке",									},
	{ .num = LEX_TO_NIGHT,			.string = L"ночи",									},
	{ .num = LEX_THROUGH,			.string = L"по",									},
	{ .num = LEX_FOREST,			.string = L"лесу",									},
	{ .num = LEX_WANDER,			.string = L"бродил",								},
	{ .num = LEX_KOL,				.string = L"коль",									},
	{ .num = LEX_WANT,				.string = L"желаешь",								},
	{ .num = LEX_WILL_TELL,			.string = L"расскажу",								},
	{ .num = LEX_NOTHING,			.string = L"ничего",								},
	{ .num = LEX_LIFE,				.string = L"жизни",									},
	{ .num = LEX_GET_BACK,			.string = L"вернуть",								},
	{ .num = LEX_ROBBERS,			.string = L"разбойники",							},
	{ .num = LEX_CAME_OUT,			.string = L"вышли",									},
	{ .num = LEX_CROWD,				.string = L"толпой",								},
	{ .num = LEX_CLOSE,				.string = L"смыкаю",								},
	{ .num = LEX_EYES,				.string = L"очи",									},
	{ .num = LEX_FELL_DOWN,			.string = L"рухнул",								},
	{ .num = LEX_DEAD,				.string = L"замертво",								},
	{ .num = STD_CLOSE_ROUND,		.string = L")", 									},
	{ .num = STD_OPEN_ROUND,		.string = L"(", 									},
	{ .num = CLOSE_ROUND, 			.string = L"всё позабыл", 							},
	{ .num = OPEN_FIGURE, 			.string = L"прыгнул со скалы", 						},
	{ .num = CLOSE_FIGURE, 			.string = L"дикий крик издав", 						},
 	{ .num = ELSE, 					.string = L"но вышло всё не так", 	    			},
 	{ .num = POW, 					.string = L"на ужин пригласил", 	    			},
	{ .num = OPEN_ROUND, 			.string = L"зашёл в тупик", 						},
 	{ .num = IF, 					.string = L"один лишь только путь", 	    		},
 	{ .num = WHILE, 				.string = L"шёл домой", 	    					},
 	{ .num = ASSIGNMENT, 			.string = L"прокричал", 	    					},
 	{ .num = SIN, 					.string = L"грохочет гром", 	    				},
 	{ .num = COS, 					.string = L"сверкает молния", 	    				},
	{ .num = FLOOR,					.string = L"на краю",								},
 	{ .num = ADD, 					.string = L"попросил", 	    						},
 	{ .num = SUB, 					.string = L"отказал", 	    						},
 	{ .num = MUL, 					.string = L"принёс", 	    						},
 	{ .num = DIV, 					.string = L"унёс", 	   								},
	{ .num = DIFF,					.string = L"на холме",								},
 	{ .num = SQRT, 					.string = L"наступала ночь", 	    				},
	{ .num = EQUAL, 				.string = L"счастье обрёл", 	    				},
	{ .num = BELOW, 				.string = L"времени всё меньше посвящает", 	   		},
	{ .num = ABOVE, 				.string = L"интерес большой нашёл", 	   			},
	{ .num = BELOW_EQUAL, 			.string = L"не хватило силы",						},
	{ .num = ABOVE_EQUAL, 			.string = L"весьма упрям",							},
	{ .num = NOT_EQUAL, 			.string = L"отличие нашёл", 						},
	{ .num = AND, 					.string = L"собрание", 	    						},
	{ .num = OR, 					.string = L"смешной совет", 	    				},
	{ .num = NOT, 					.string = L"он не знает", 	    					},
 	{ .num = SEQUENTIAL_OP, 		.string = L"хей", 	    							},
 	{ .num = COMMA_OP, 				.string = L"во мраке ночи", 	    				},
 	{ .num = INIT_TYPE, 			.string = L"по лесу бродил", 						},
	{ .num = INPUT, 				.string = L"хой", 	    							},
 	{ .num = PRINTF, 				.string = L"коль желаешь расскажу", 				},
 	{ .num = RETURN, 				.string = L"ничего в жизни не вернуть", 			},
 	{ .num = BREAK, 				.string = L"разбойники вышли толпой", 	    		},
 	{ .num = CONTINUE, 				.string = L"смыкаю очи", 							},
	{ .num = ABORT,					.string = L"рухнул замертво",						},
	{ .num = AMOUNT_OF_KEYWORDS 														}};
