#pragma once

#include "KeyWords.hpp"

KeyWord keywords[] = {
	{ .num = CLOSE_ROUND, 	.string = ")", 			},
	{ .num = OPEN_FIGURE, 	.string = "{", 			},
	{ .num = CLOSE_FIGURE, 	.string = "}", 			},
 	{ .num = ELSE, 			.string = "else", 	    },
 	{ .num = POW, 			.string = "^", 	    	},
	{ .num = OPEN_ROUND, 	.string = "(", 			},
 	{ .num = IF, 			.string = "if", 	    },
 	{ .num = WHILE, 		.string = "while", 	    },
 	{ .num = ASSIGNMENT, 	.string = "=", 	    	},
 	{ .num = SIN, 			.string = "sin", 	    },
 	{ .num = COS, 			.string = "cos", 	    },
	{ .num = FLOOR,			.string = "floor",		 },
 	{ .num = ADD, 			.string = "+", 	    	},
 	{ .num = SUB, 			.string = "-", 	    	},
 	{ .num = MUL, 			.string = "*", 	    	},
 	{ .num = DIV, 			.string = "/", 	   		},
	{ .num = DIFF,			.string = "diff",		},
 	{ .num = SQRT, 			.string = "sqrt", 	    },
	{ .num = EQUAL, 		.string = "equal", 	    },
	{ .num = BELOW, 		.string = "below", 	   	},
	{ .num = ABOVE, 		.string = "above", 	   	},
	{ .num = BELOW_EQUAL, 	.string = "below_equal",},
	{ .num = ABOVE_EQUAL, 	.string = "above_equal",},
	{ .num = NOT_EQUAL, 	.string = "not_equal", 	},
	{ .num = AND, 			.string = "and", 	    },
	{ .num = OR, 			.string = "or", 	    },
	{ .num = NOT, 			.string = "!", 	    	},
 	{ .num = SEQUENTIAL_OP, .string = ";", 	    	},
 	{ .num = COMMA_OP, 		.string = ",", 	    	},
 	{ .num = INIT_TYPE, 	.string = "double", 	},
	{ .num = INPUT, 		.string = "input", 	    },
 	{ .num = PRINTF, 		.string = "printf", 	},
 	{ .num = RETURN, 		.string = "return", 	},
 	{ .num = BREAK, 		.string = "break", 	    },
 	{ .num = CONTINUE, 		.string = "continue", 	},
	{ .num = ABORT,			.string = "abort",		},
	{ .num = AMOUNT_OF_KEYWORDS }};
