#pragma once

#include "KeyWords.hpp"

KeyWord keywords[] = {
	{ .num = STD_CLOSE_ROUND,		.string = L")", 									},
	{ .num = STD_OPEN_ROUND,		.string = L"(", 									},
	{ .num = CLOSE_ROUND, 			.string = L"всё_позабыл", 							},
	{ .num = OPEN_FIGURE, 			.string = L"прыгнул_со_скалы", 						},
	{ .num = CLOSE_FIGURE, 			.string = L"дикий_крик_издав", 						},
 	{ .num = ELSE, 					.string = L"но_вышло_всё_не_так", 	    			},
 	{ .num = POW, 					.string = L"на_ужин_пригласил", 	    			},
	{ .num = OPEN_ROUND, 			.string = L"зашёл_в_тупик", 						},
 	{ .num = IF, 					.string = L"один_лишь_только_путь", 	    		},
 	{ .num = WHILE, 				.string = L"шёл_домой", 	    					},
 	{ .num = ASSIGNMENT, 			.string = L"прокричал", 	    					},
 	{ .num = SIN, 					.string = L"грохочет_гром", 	    				},
 	{ .num = COS, 					.string = L"сверкает_молния", 	    				},
	{ .num = FLOOR,					.string = L"на_краю",								},
 	{ .num = ADD, 					.string = L"попросил", 	    						},
 	{ .num = SUB, 					.string = L"отказал", 	    						},
 	{ .num = MUL, 					.string = L"принёс", 	    						},
 	{ .num = DIV, 					.string = L"унёс", 	   								},
	{ .num = DIFF,					.string = L"на_холме",								},
 	{ .num = SQRT, 					.string = L"наступала_ночь", 	    				},
	{ .num = EQUAL, 				.string = L"счастье_обрёл", 	    				},
	{ .num = BELOW, 				.string = L"времени_всё_меньше_посвящает", 	   		},
	{ .num = ABOVE, 				.string = L"интерес_большой_нашёл", 	   			},
	{ .num = BELOW_EQUAL, 			.string = L"не_хватило_силы",						},
	{ .num = ABOVE_EQUAL, 			.string = L"весьма_упрям",							},
	{ .num = NOT_EQUAL, 			.string = L"отличие_нашёл", 						},
	{ .num = AND, 					.string = L"собрание", 	    						},
	{ .num = OR, 					.string = L"смешной_совет", 	    				},
	{ .num = NOT, 					.string = L"он_не_знает", 	    					},
 	{ .num = SEQUENTIAL_OP, 		.string = L"хей", 	    							},
 	{ .num = COMMA_OP, 				.string = L"во_мраке_ночи", 	    				},
 	{ .num = INIT_TYPE, 			.string = L"по_лесу_бродил", 						},
	{ .num = INPUT, 				.string = L"хой", 	    							},
 	{ .num = PRINTF, 				.string = L"коль_желаешь_расскажу", 				},
 	{ .num = RETURN, 				.string = L"ничего_в_жизни_не_вернуть", 			},
 	{ .num = BREAK, 				.string = L"разбойники_вышли_толпой", 	    		},
 	{ .num = CONTINUE, 				.string = L"смыкаю_очи", 							},
	{ .num = ABORT,					.string = L"рухнул_замертво",						},
	{ .num = AMOUNT_OF_KEYWORDS 														}};
