#!/bin/bash

# cmake -S ./ -B build/Release -DCMAKE_BUILD_TYPE=Release
# cmake --build build/Release && ./build/Release/Backend

cmake -S ./ -B build/Debug -DCMAKE_BUILD_TYPE=Debug
cmake --build build/Debug && ./build/Debug/Backend

nasm -f elf64 printf.s -o build/printf.o -l build/printf.lst && \
nasm -f elf64 scanf.s -o build/scanf.o -l build/scanf.lst && \
nasm -f elf64 nasm.asm -o build/nasm.o -l build/nasm.lst && \
ld -o build/nasm build/nasm.o build/printf.o build/scanf.o && \
./build/nasm
