#pragma once

#define _NUM(val) 								CreateNode(NUMBER, 					{.val_num 		= val}, 			NULL, NULL,  NULL)
#define _ID(id_num) 							CreateNode(IDENTIFIER, 				{.val_id  		= id_num}, 			NULL, NULL,  NULL)
#define _KEYWORD(key_word_num, left, right)		CreateNode(KEYWORD,					{.val_key_word 	= key_word_num},	NULL, NULL,	 NULL)
#define _FUNC_DEF(id_func_num, left, right) 	CreateNode(FUNCTION_DEFINITION, 	{.val_func_def  = id_func_num}, 	left, right, NULL)
#define _PARAMETERS(left, right) 				CreateNode(PARAMETERS, 				{}, 								left, right, NULL)
#define _VAR_DEC(var_id, left, right) 			CreateNode(VAR_DECLARATION, 		{.val_decl_var	= var_id}, 			left, right, NULL)
#define _CALL(left, right) 						CreateNode(CALL, 					{},					 				left, right, NULL)

#define _ELSE(left, right)						CreateNode(KEYWORD,					{.val_key_word = ELSE},				left, right, NULL)
#define _POW(left, right) 						CreateNode(KEYWORD, 				{.val_key_word = POW}, 				left, right, NULL)
#define _IF(left, right) 						CreateNode(KEYWORD, 				{.val_key_word = IF}, 				left, right, NULL)
#define _WHILE(left, right) 					CreateNode(KEYWORD, 				{.val_key_word = WHILE},			left, right, NULL)
#define _ASSIGNMENT(left, right) 				CreateNode(KEYWORD, 				{.val_key_word = ASSIGNMENT}, 		left, right, NULL)
#define _SIN(left, right) 						CreateNode(KEYWORD,  				{.val_key_word = SIN}, 				left, right, NULL)
#define _COS(left, right) 						CreateNode(KEYWORD,  				{.val_key_word = COS}, 				left, right, NULL)
#define _FLOOR(left, right)						CreateNode(KEYWORD,  				{.val_key_word = FLOOR}, 			left, right, NULL)
#define _ADD(left, right) 						CreateNode(KEYWORD,  				{.val_key_word = ADD}, 				left, right, NULL)
#define _SUB(left, right) 						CreateNode(KEYWORD,  				{.val_key_word = SUB}, 				left, right, NULL)
#define _MUL(left, right) 						CreateNode(KEYWORD,  				{.val_key_word = MUL}, 				left, right, NULL)
#define _DIV(left, right) 						CreateNode(KEYWORD,  				{.val_key_word = DIV}, 				left, right, NULL)
#define _DIFF(left, right)						CreateNode(KEYWORD,					{.val_key_word = DIFF},				left, right, NULL)
#define _SQRT(left, right)						CreateNode(KEYWORD,  				{.val_key_word = SQRT}, 			left, right, NULL)
#define _EQUAL(left, right)						CreateNode(KEYWORD,					{.val_key_word = EQUAL},			left, right, NULL)
#define _BELOW(left, right)						CreateNode(KEYWORD,					{.val_key_word = BELOW},			left, right, NULL)
#define _ABOVE(left, right)						CreateNode(KEYWORD,					{.val_key_word = ABOVE},			left, right, NULL)
#define _BELOW_EQUAL(left, right)				CreateNode(KEYWORD,					{.val_key_word = BELOW_EQUAL},		left, right, NULL)
#define _ABOVE_EQUAL(left, right)				CreateNode(KEYWORD,					{.val_key_word = ABOVE_EQUAL},		left, right, NULL)
#define _NOT_EQUAL(left, right)					CreateNode(KEYWORD,					{.val_key_word = NOT_EQUAL},		left, right, NULL)
#define _AND(left, right)						CreateNode(KEYWORD,					{.val_key_word = AND},				left, right, NULL)
#define _OR(left, right)						CreateNode(KEYWORD,					{.val_key_word = OR},				left, right, NULL)
#define _NOT(left, right)						CreateNode(KEYWORD,					{.val_key_word = NOT},				left, right, NULL)
#define _SEQUENTIAL_OP(left, right) 			CreateNode(KEYWORD,  				{.val_key_word = SEQUENTIAL_OP}, 	left, right, NULL)
#define _COMMA_OP(left, right) 					CreateNode(KEYWORD,  				{.val_key_word = COMMA_OP}, 		left, right, NULL)
#define _PRINTF(left, right) 					CreateNode(KEYWORD,  				{.val_key_word = PRINTF}, 			left, right, NULL)
#define _RETURN(left, right) 					CreateNode(KEYWORD,  				{.val_key_word = RETURN}, 			left, right, NULL)
#define _INIT_TYPE() 							CreateNode(KEYWORD,  				{.val_key_word = INIT_TYPE}, 		NULL, NULL,  NULL)
#define _INPUT() 								CreateNode(KEYWORD,  				{.val_key_word = INPUT}, 			NULL, NULL,  NULL)
#define _BREAK() 								CreateNode(KEYWORD,  				{.val_key_word = BREAK}, 			NULL, NULL,  NULL)
#define _CONTINUE()								CreateNode(KEYWORD,  				{.val_key_word = CONTINUE}, 		NULL, NULL,  NULL)
#define _ABORT()								CreateNode(KEYWORD,					{.val_key_word = ABORT},			NULL, NULL,  NULL)

#define dL doDifferentiation(node->left, id_name_table)
#define dR doDifferentiation(node->right, id_name_table)

#define eR Eval(node->right)
#define eL Eval(node->left)

#define cL doCopySubtree(node->left)
#define cR doCopySubtree(node->right)
#define cP doCopySubtree(node)
